
spring :
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  #  config:
  #    import: optional:bashrc:.env
  datasource:
    url: jdbc:postgresql://localhost:5432/sampleDB
    username: postgres
    password: root
